### ISSUE TITLE
Infinite Fluids Appears to not work with Terrafirmacraft fluids (1.7.10)

### ISSUE THREAD

**Issue by drhaber** [josephcsible/InfiniteFluids#6]
My config: 
W/ TFC finite fluids on
> general {
    # A list of fluids that will be infinite inside of the Nether (and any mod-added dimensions where water can't be placed) [default: ]
    S:fluidsInsideNether <
     >

    # A list of fluids that will be infinite outside of the Nether (or any mod-added dimensions where water can't be placed) [default: [minecraft:water]]
    S:fluidsOutsideNether <
        terrafirmacraft:SaltWaterStationary
        terrafirmacraft:SaltWater
     >

    # Whether to invert the function of fluidsInsideNether (i.e., make all fluids infinite except those listed) [default: false]
    B:invertInsideNether=false

    # Whether to invert the function of fluidsOutsideNether (i.e., make all fluids infinite except those listed) [default: false]
    B:invertOutsideNether=false
}

Additionally when I toggle the Finite fluids option from within Terrafrimcraft to off the issue is reversed where no fluids are finite

**Comment by josephcsible** [comment]
I don't think I'm going to do anything about this for 2 reasons:

1. This is a problem because TerraFirmaCraft in 1.7.10 [overrides `BlockDynamicLiquid.updateTick` without ever calling the superclass method](https://github.com/Deadrik/TFCraft/blob/74c3e48f499872710160c29835e6470f5367d52a/src/Common/com/bioxx/tfc/Blocks/Liquids/BlockCustomLiquid.java#L330-L470), so no Forge code has a chance to run in it. This means the only way I could make this support TerraFirmaCraft for 1.7.10 would be to add custom code just for it, which seems like an unreasonable thing to do, since they could easily make it work on their end.
2. This problem has been fixed properly since Minecraft 1.10.2, when [I got `CreateFluidSourceEvent` added to Forge](https://github.com/MinecraftForge/MinecraftForge/commit/fc43ebbd7e88a2590797ac14639b97c862a9dc9f). Minecraft 1.7.10 is over 10 years and 8 major versions old today, so I don't really want to maintain mods for it anymore, since it would require doing a lot of things the hard way that have long since been solved the easy way. If you're stuck on 1.7.10 because of other mods that only exist on it, then perhaps you should nag the authors of those mods to update, rather than nagging others to backport things.
